version: '3.7'
services:
    # 1. Laravel PHP-FPM 服務
    app:
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: swift-3pl-app
        container_name: swift_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./backend:/var/www/html
        depends_on:
            - mysql_db
            - redis
        networks:
            - swift-network

    # 2. Nginx Web 服務
    nginx:
        image: nginx:stable-alpine
        container_name: swift_nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./backend:/var/www/html
            - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf 
        depends_on:
            - app
        networks:
            - swift-network
    
    # 3. MySQL 資料庫服務
    mysql_db:
        image: mysql:8.0
        container_name: swift_mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: swift_3pl
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: sail
            MYSQL_PASSWORD: password
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "33061:3306"
        networks:
            - swift-network

    # 4. Redis 快取與隊列服務
    redis:
        image: redis:alpine
        container_name: swift_redis
        restart: unless-stopped
        networks:
            - swift-network
    
    # 5. Queue Worker 服務
    queue:
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: swift-3pl-app
        container_name: swift_queue_worker
        restart: unless-stopped
        command: php /var/www/html/artisan queue:work --queue=default,picking_speed,webhook_high_priority --tries=3 --timeout=60
        volumes:
            - ./backend:/var/www/html
        depends_on:
            - mysql_db
            - redis
            - app
        networks:
            - swift-network

volumes:
    db_data:

networks:
    swift-network:
        driver: bridge
