name: CI/CD Docker Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build PHP/Laravel App Image
      uses: docker/build-push-action@v5
      with:
        context: ./backend 
        file: ./backend/Dockerfile
        push: false
        tags: swift-3pl-app:latest

    - name: Bring up Docker Compose (DB/Redis)
      run: |
        cp ./backend/.env.example ./backend/.env
        docker compose up -d mysql_db redis
        
    - name: Wait for DB to be ready
      run: sleep 10 
        
    - name: Run Composer Install
      run: docker compose run --rm app composer install --working-dir=/var/www/html --no-dev --prefer-dist

    - name: Run Database Setup (Key, Migrations, Seed)
      run: |
        docker compose exec app php artisan key:generate
        docker compose exec app php artisan migrate --path=database/migrations/landlord --force
        docker compose exec app php artisan db:seed --class=DemoDatabaseSeeder --force
        
    - name: Clean up Docker containers
      if: always()
      run: docker compose down -v
